name: BUILD-TEST

on:
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches every branch
      - '!main'   # excludes master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: test build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: lefanhu/interqu-angular-app:latest